package po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import utility.BaseUtil;

/*
 * In this NodeTypeBean, in my opinion, 
 * I choose sensorTypeListBean as its member for the following reasons: 
 * 				1. we have chosen a relation table named Node_SensorType, so every nodeType 
 * 					will be related with at least one sensorType. 
 * 				2. we apparently do not want to create another class to specify the relationship
 * 					between nodeType and sensorType.
 * So, based on these, I decide this.		 		
 */
public class NodeTypeBean implements Serializable {
	private static final long serialVersionUID = 1L;
	private String Id;
	private String nodeType;
	private String remark;
	private List<SensorTypeBean> sensorTypeListBean;

	public NodeTypeBean() {

		sensorTypeListBean = new ArrayList<SensorTypeBean>();
	}

	public NodeTypeBean(String aNodeType, String aRemark) {

		this();
		this.nodeType = aNodeType;
		this.remark = aRemark;
	}

	/*
	 * Just to list the string of result
	 */
	public String toString() {
		return "nodeType = " + nodeType + ", remark = " + remark + "\n"
				+ sensorTypeListBean.toString();
	}

	/*
	 * add necessary sensorType
	 */
	public void addSensorType(SensorTypeBean sensorTypeBean) {

		if (sensorTypeBean != null) {

			sensorTypeListBean.add(sensorTypeBean);
		}
	}

	/*
	 * delete the selected sensorType just by its name for it's unique,
	 * whatever.
	 */
	public void deleteSensorType(String sensorName) {

		if (sensorName == null || sensorName.equals("")) {

			return;
		}
		for (SensorTypeBean sensorTypeBean : sensorTypeListBean) {

			if (sensorName.equals(sensorTypeBean.getSensorName())) {

				sensorTypeListBean.remove(sensorTypeBean);
				return;
			}
		}
	}

	public boolean isContainSensorType(String sensorName) {

		for (SensorTypeBean tempBean : this.getSensorTypeListBean()) {

			if (BaseUtil.StringSafe(tempBean.getSensorName())
					.equals(sensorName)) {

				return true;
			}
		}

		return false;
	}

	/*
	 * delete the selected sensorType by detecting whether it's contained in
	 * sensorTypeList.
	 */
	public void deleteSensorType(SensorTypeBean sensorTypeBean) {

		if (sensorTypeBean == null) {

			return;
		}

		sensorTypeListBean.remove(sensorTypeBean.getSensorName());
	}

	/*
	 * Then I think it's generated by the system, just setter and getter as we
	 * all know well.
	 */
	public List<SensorTypeBean> getSensorTypeListBean() {
		return sensorTypeListBean;
	}

	public void setSensorTypeListBean(List<SensorTypeBean> sensorTypeListBean) {
		this.sensorTypeListBean = sensorTypeListBean;
	}

	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	public String getNodeType() {
		return nodeType;
	}

	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
}
